from random import *
class Quote:
	def __init__(self):
		self.quotes = [
		"“I’m not crazy. I’m enlightened.”"
		,"Brandon-“Erik, start counting backwards from 100.” Erik-“Seven– fuck.”"
		,"“I’m going to speak in Broman Morse code. Broman, Broman, Broman, Brroooooman, Brroooooman, Brroooooman, Broman, Broman, Broman. That SOS.”"
		,"“No knifu no lifu”"
		,"“How could I lose these statistically average rolls???”"
		,"“Such pigs don't deserve to touch enlightened beings such as myself”"
		,"“Satan Is My Only Senpai”"
		,"“They don’t have to be free as long as they’re happy???”"
		,"“That’s a poor quality snail right there”"
		,"“Fuck me Sans”"
		,"“Just because they like to have gay sex together doesn't mean they're disgusting”"
		,"“Also we didn't have these problems until michael invited everyone from here to timbuktu”"
		,"“Statistics make more!!!”"
		,"Joey - “That’s why you lost fucko!”"
		,"“I ripped her apart”"
		,"“We're spitting water that's been put out by a fire”"
		,"“I want to be that guy that just fucks you.”"
		,"“She could be a fox. I wouldn’t mind.”"
		,"“I’ve never seen such a sexualized corpse”"
		,"“All are one within the greater gas”"
		,"“If you are what you eat then you are an ASS”"
		,"“I'm J.K. Park; I steal people's wives from their scarves…”"
		,"“You don't fuck America? How unpatriotic of you.”"
		,"“I will. I will eat your type 7 ass”"
		,"“Erik is the center of the world and he knows it”"
		,"“His passive is that he doesn’t have to pay child support so it's a pretty powerful combo!”-Alex"
		,"“That's hot”"
		,"“Why do I find it therapeutic to break your heart?”"
		,"“Orlando Bloom is hot”, “Orlando Bloom is hot. That’s not a quote it’s a fucking fact”"
		,"“I’m starting with c_nt Broman”"
		,"“I’m going to eat my own ass, brb.” (upon return)–>“Mmmmm that kiwi flavor.”"
		,"“My selfish desires??? I’m a fucking tree!! Let me be your friend. (quieter) I want to be your friend...”"
		,"“They could all be old brown dudes”-Jackson"
		,"“Turn that poop into rage”"
		,"“I know Georgians. They deserved it.”"
		,"Jade-“Every time you do something like that I just have the irresistible urge to put bullets in you”, Erik-“That's pretty hot”- Erik"
		,"“We're not playing Hearthstone you stupid bitch!”"
		,"“I'm pretty sure if I poisoned your cats they would die”"
		,"“West House is closed because Sarah Crawford is snorting coke in Cuba”"
		,"“When people actually belong in a zoo, I get a little angry dude”-Jade"
		,"“Technically you can’t suck; but you can still blow.”-Alex"
		,"“Any time you start a sentence with ‘all I’m saying’ you should probably just shut up.”-Brandon @ Erik"
		,"“Part of it is just that I like to see Anderson Cooper wet.”"
		,"“What I’m trying to say is: you’re improving”"
		,"“There’s no such thing as a good person there’s only people who haven’t realized.”"
		,"“I like my men how I like my coffee; ground up and in the freezer.”"
		,"“I don't know and I don’t care. I just want to eat your hair.”"
		,"“Where's my smiley face?!?!?”"
		,"“You’re playing with water”-Alex"
		,"“That’s a big Gnar”-Jackson"
		,"“I do not condone beastiality”"
		,"“That's how I harvest my weed. Ehhhh! Ehhhhhh!!!”"
		,"“My physical prowess is essentially average”-Alex"
		,"“My physical Jackson is essentially average”-Erik"
		,"“I don’t know I guess I just don’t want to be fucked by a toucan.”, “I mean I wasnt that against it.”"
		,"“The concept of McDonalds as a concept is not immoral”"
		,"“Yeaaaaah boiiiiiii this American Pie”-Jackson/Brandon"
		,"“I'm either sketchy or suspiciously not sketchy” Jackson"
		,"“I’m arguably not ranting”"
		,"“I don’t want to prove my point”"
		,"“Floop is a fun word to say”"
		,"“We’re all squeaky toys in the end”"
		,"“DYLAN’S GOT HIM BY THE BALLS”-The eternal words of Jade"
		,"“By acting like someone you are taking the action they would logically take. Whenever you take action that action becomes the action you would logically take as you are currently taking it and there for you are acting like yourself. So when you are acting like a person you are also acting like yourself because you would pretend to be them”"
		,"“Waterboarding in the streets, senpai in the sheets.”"
		,"“You don’t find stillborn babies appetizing?”"
		,"“They have ridges everywhere. I wouldn’t be surprised if their penises were flat.”"
		,"“Crippled people hate veterans”"
		,"“Buffalo is the south of the north.”"
		,"“Let’s drop kick Bella Wong”"
		,"“I could see B-Wong on Fox news”"
		,"“Who’s complaining about Erik at this table? I want names...I want addresses...I want family members”"
		,"“We don’t need to outrun him, we just need to outrun Jackson”-Alex"
		,"“You don’t have the philosophical knowledge to understand your meme”"
		,"“The definition of a gas is that any gas anywhere is a gas”"
		,"“My body is ardo”"
		,"“Really, we couldn’t get ‘laid’?”"
		,"“Snap back to reality, hey it’s Sean Hannity”"
		,"“There’s no way we could lose this game”"
		,"“There’s no way we could win this game”"
		,"“Deadlydad69”"
		,"“MAGES SHOULDN'T WEAR JACK SHIT”, “Unless your pants give you mana or some shit, you shouldn’t be wearing them!”"
		]
	def getQuote(self):
		return self.quotes[randint(0, len(self.quotes))]
		